### PR TITLE
implemented sendConfirmationBlocks

### PR DESCRIPTION
**Pull request by tomijaga**
Resolves: #107
Need to get more information on the flow of data in order to properly write docs for these new methods

### CODE REVIEW

**Comment by zinoadidi** [comment]
For this one I meant maybe we can create new doc task and move on with this

**Review by zinoadidi — APPROVED** [review]

**Comment by zinoadidi** [comment]
Also the tests are missing from this as I understand?

**Comment by tomijaga** [comment]
@zinoadidi creating a new task for the docs and test are fine

**Comment by tomijaga** [comment]
> Need to get more information on the flow of data in order to properly write docs for these new methods

I just got more detail on this feature and have concluded that it wouldn't be useful to add it to the sdk.
This is because this requests can only be accessed by the nodes and not the client.

So @zinoadidi don't merge this.

**Comment by zinoadidi** [comment]
Pull rejected

**Pull request closed without merging**
