### PR TITLE
Implemented interface for ConfirmationValidator

### PR DESCRIPTION
**Pull request by nishp77**
Please check it out  #35

### CODE REVIEW

**Comment by nishp77** [comment]
Do we write tests?

**Review by sno2 — CHANGES_REQUESTED** [review]
Awesome, but can you please rename the `confirmationvalidator` folder to `confirmation-validator`?

**Comment by sno2** [comment]
> Do we write tests?

No, not for types.

**Comment by sno2** [comment]
I think you accidentally pushed to the same branch of your fork.

**Review by sno2 — APPROVED** [review]
LGTM, thanks for reviewing my changes and fixing the branch issues👍

**Comment by sno2** [comment]
@nishp77  Please send your account number here so that payments team can pay you for your work soon.

**Comment by nishp77** [comment]
c81061eb20ee1379ab98b6f5a125ebd0955278e36513eabd8d319967bb61d7e8

**Pull request merged**
