### PR TITLE
feat: added getCrawlStatus

### PR DESCRIPTION
**Pull request by tomijaga**
Resolves: #85
Resolves: #95

### CODE REVIEW

**Comment by tomijaga** [comment]
Having errors when making crawl post request 

This is the crawl documentation
image

It says you only need the data and signature keys, but when i call the `startCrawl()` method i get an error that says i need to add the nodeIdentifier property
image

**Review by zinoadidi — APPROVED** [review]

**Comment by zinoadidi** [comment]
@tomijaga I was looking at the account manager,
it seems to be doing a lot more things; 
could it be that we are missing something that they are doing there?

**Review by zinoadidi — CHANGES_REQUESTED** [review]
Awaiting response

**Comment by tomijaga** [comment]
I only added the functions that were related to thenewboston or that directly called the API. Most of the functions there are specific to the Account Manager. 

You can double check to see if there is anything missing. There is always a possibility that i might have missed or skipped something

**Comment by zinoadidi** [comment]
@tomijaga lets keep it open until we have further clarification.
thanks for your efforts!

**Comment by tomijaga** [comment]
Post request structure is wrong. Should be:

```
message:{
    crawl: "start" | "stop"
},
node_identifier: 565723676...,
signature: 54cd54bvd...
```

Solution can be found here: https://github.com/thenewboston-developers/Account-Manager/blob/master/src/renderer/hooks/useCleanSockets.tsx

**Comment by zinoadidi** [comment]
Good job finding it!.
When you have time do update the solution so we can close it

**Review by zinoadidi — APPROVED** [review]

**Pull request merged**
