### PR TITLE
feat: Bulk payments

### PR DESCRIPTION
**Pull request by tomijaga**
Resolves: #83
## Implemented Bulk Payments. 
I don't know if this is the best implementation. 
I used the **Transaction[]** type instead of the **TransferDetails** class for the 
methods `createTransaction()` and `sendBulkTransactions()`

Also Should i make the internal methods private

### CODE REVIEW

**Comment by zinoadidi** [comment]
i think internal methods can stay private;
this change contains breaking changes so we (I) will need to make sure it's properly reflected for users.
we will need to add tests as well as update existing ones that should be broken now due to the change.

As I understand, all future transactions need to be in an array, single or multiple yes?

also, I created and linked an issue to it

**Review by zinoadidi — CHANGES_REQUESTED** [review]
Need to add tests/update existing tests as well

**Comment by tomijaga** [comment]
@zinoadidi yh all transactions have to be in an array. Are u saying that I should remove the `sendCoins()` method. And instead, just have one method that can send single and multiple transactions

**Comment by zinoadidi** [comment]
@tomijaga i think it's fine to leave the `sendCoin` there.
but logically, it will be an obsolute means but makes sense to have something where user can show the correct intent what kind of transaction they are performing

**Comment by zinoadidi** [comment]
@tomijaga needs also tests then me can merge it and move to next one

**Comment by tomijaga** [comment]
@zinoadidi  I'm currently doing school work rn but i will get the tests done at the end of the day. You can put up issues for the other changes and i will get to them as time permits me

**Review by zinoadidi — APPROVED** [review]

**Pull request merged**
