### PR TITLE
Feat: getCleanStatus(), startClean() and stopClean()

### PR DESCRIPTION
**Pull request by tomijaga**
Resolves: #86

### CODE REVIEW

**Comment by zinoadidi** [comment]
hi, good job so far but missing tests.

**Comment by zinoadidi** [comment]
@tomijaga do you want to create a new task for the test as it's taking a bit more time to test this?

**Comment by AbhayAysola** [comment]
@zinoadidi @tomijaga I can work on the tests along with the rest of Bank class methods

**Comment by tomijaga** [comment]
@AbhayAysola Yh you can take over for the tests

**Comment by zinoadidi** [comment]
@AbhayAysola kindly make a task for it as well, then the bounty is correctly assigned to it

**Comment by AbhayAysola** [comment]
> @AbhayAysola kindly make a task for it as well, then the bounty is correctly assigned to it

Sure

**Comment by zinoadidi** [comment]
Tests are available through https://github.com/thenewboston-developers/thenewboston-js/issues/105

**Pull request merged**
