### PR TITLE
Fix the minified Browserify file

### PR DESCRIPTION
**Pull request by AbhayAysola**

### CODE REVIEW

**Review by sno2 — CHANGES_REQUESTED** [review]
Thanks, I'd pull this in now, but your commits are mixed between PRs.

**Comment by AbhayAysola** [comment]
Yaa, sorry about that. I'll fix it now. 😓

**Review by sno2 — APPROVED** [review]
LGTM

**Comment by Sulaiman001** [comment]
@sno2  please which issue is this PR is linked.

**Comment by AbhayAysola** [comment]
@Sulaiman001 I don't think there is an issue for this PR, since I opened this PR when I was trying to use the minified file. I am sorry if I was supposed to open an issue first.

**Comment by sno2** [comment]
> @sno2  please which issue is this PR linked to.

Sorry, I didn't realize that we needed issues for all tasks.  I can't make it right now, but I'll create the issue later today.

**Pull request merged**
