### PR TITLE
Add Bank tests

### LINKED ISSUE #90: [Task] Test bank class
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview
Parent:  https://github.com/thenewboston-developers/thenewboston-js/issues/75
Test bank class in the SDK and methods under the bank class.

## Behavior

All tests you change/add need to be passing tests both locally and in Github Actions

```ts
/* code examples are awesome */
```

### PR DESCRIPTION
**Pull request by AbhayAysola**
Closes #90 
Accout Number: 8928526805de48e4bf2ed2a9b4b839e6b2603018ecdfbf4cffdb2065e01a3ed1

### CODE REVIEW

**Comment by AbhayAysola** [comment]
I tried checking the signature of the returned objects from the functions but I couldn't find a way to do that in Jest. For now I just checked if they are truthy values but it would be better if we actually checked the objects. Any thoughts? @zinoadidi @tomijaga

**Comment by zinoadidi** [comment]
you can mock
 
` return await super.getPaginatedData<PaginatedTransactionEntry & PaginatedEntry>("/bank_transactions", options);`

using mocha and simulate the return data since we have all the objects there as various types and classes,
it takes couple of minutes yes but the sooner we start generating those data, the easier it is for future 

Maybe a folder with all test data could be added as well if needed and then its reuasble

**Comment by AbhayAysola** [comment]
> you can mock
> 
> ` return await super.getPaginatedData<PaginatedTransactionEntry & PaginatedEntry>("/bank_transactions", options);`
> and all similar calls using mocha and simulate the return data since we have all the objects there as various types and classes,
> it takes couple of minutes yes but the sooner we start generating those data, the easier it is for future
> 
> Maybe a folder with all test data could be added as well if needed and then its reuasble

Hmm I've never done anything like that. Mind pointing me towards some resources to get started?

**Comment by zinoadidi** [comment]
@AbhayAysola 
This one talks about how to test HTTP requests and co by mocking away the connection between the server and the client (us) so that client is independent during testing phase and works based on his own data / responses and terms >> https://scotch.io/tutorials/nodejs-tests-mocking-http-requests

This one clarify how testing asynchronous methods works using mocha >> https://staxmanade.com/2015/11/testing-asyncronous-code-with-mochajs-and-es7-async-await/

**Comment by AbhayAysola** [comment]
Thanks @zinoadidi I'll install mocha and work on that

**Comment by AbhayAysola** [comment]
@zinoadidi Should I replace Jest with Mocha?

**Comment by zinoadidi** [comment]
actually, they can be there together as they provide different functionalities. 
Not sure if the just guys added mocking functionalities after some time; would be worth investigating after implementation what is possible with only jest and what was needed more from mocha

**Comment by AbhayAysola** [comment]
@zinoadidi I added nock but I don't think Mocha and Chai are needed for our use case. I also added the test data, would like for you take a look at it.

**Review by zinoadidi — APPROVED** [review]
good job. i think nock solves the problem; no need for mocking just yet.

**Comment by AbhayAysola** [comment]
> good job. i think nock solves the problem; no need for mocking just yet.

I still need to add the test data for the rest of the tests @zinoadidi

**Comment by tomijaga** [comment]
@AbhayAysola  @zinoadidi The `getTransactions()` test fails because the data does not stay the same. There will be newer transactions made on the network which will always cause the test to fail.

Also the other tests only check if the method returns a value. Is this enough for a test?

I'm trying to make test for my PR but i can't find a way to check the the data returned by the network api because they are always changing

**Comment by zinoadidi** [comment]
@tomijaga Maybe you want to return mock data like the example here using this nock thing @AbhayAysola added?
SO it doesn't check the actual network 

You can inspect the account manager and extract some sample data from the network tab from requests its making and use that in your solution

**Comment by AbhayAysola** [comment]
> @AbhayAysola can you make a task for missing data what you haven't added yet

Sure will do

**Pull request merged**
