### PR TITLE
Update package.json to fix npm package issue #69

### LINKED ISSUE #69: [Task] Fix npm deployments (extra 2000 TNBC bounty available)
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

When you run `npm install thenewboston`, there's no `dist` directory. You can't then just `require("thenewboston")` without going inside `node_modules/thenewboston` and running `npm install && npm run build` first.

If you `require("thenewboston")` without going inside the module and running `npm install && npm run build` first, you get an error:

```
node:internal/modules/cjs/loader:352
      throw err;
      ^

Error: Cannot find module '/Users/mieszkokycermann/Desktop/Projects/Mieszko-Exchange/Crypto-API/node_modules/thenewboston/dist/index.js'. Please verify that the package.json
 has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:344:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:557:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:911:27)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/mieszkokycermann/Desktop/Projects/Mieszko-Exchange/Crypto-API/src/crypto/impl/tnb.js:4:55)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/mieszkokycermann/Desktop/Projects/Mieszko-Exchange/Crypto-API/node_modules/thenewboston/package.json',
  requestPath: 'thenewboston'
}
```

When you `npm install` in your project root, the TNB module resets and you have to manually go in and set it up again.

## Behavior

This task is complete when you can do `npm install thenewboston` and that installs with the `dist` directory already there (preferably deploy that directory to npm for faster installs but a pre-install script works too if that's a thing).

### PR DESCRIPTION
**Pull request by AbhayAysola**
This commit should fix #69 
Account Number: 8928526805de48e4bf2ed2a9b4b839e6b2603018ecdfbf4cffdb2065e01a3ed1

### CODE REVIEW

**Comment by AbhayAysola** [comment]
@Kycermann @zinoadidi This works fine on my system, but I would like it if you could also test it locally. To do that open up this PR locally and run `npm pack` in the directory. After that command executes, you should see a `thenewboston-1.0.2.tgz` file in the directory. After that make a new directory and type `npm install <the path of the generated .tgz file>` . Once that is done installing simply run `node` in the newly created dir and try doing `require('thenewboston/')`. If all goes well it should work :)

**Comment by zinoadidi** [comment]
hi, i wrote @Kycermann to test as well but anyone can test it and give feedback; 
Once i am sure everything now works as expected i will approve PR

**Comment by Kycermann** [comment]
@AbhayAysola I get an error when running npm install thenewboston.tgz

```
node:internal/modules/cjs/loader:928
  throw err;
  ^


Error: Cannot find module 'regenerator-runtime/runtime'
Require stack:
- /Users/mieszkokycermann/Desktop/Projects/thenewboston-js/node_modules/thenewboston/dist/index.js
- /Users/mieszkokycermann/Desktop/Projects/thenewboston-js/test.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/mieszkokycermann/Desktop/Projects/thenewboston-js/node_modules/thenewboston/dist/index.js:101:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/mieszkokycermann/Desktop/Projects/thenewboston-js/node_modules/thenewboston/dist/index.js',
    '/Users/mieszkokycermann/Desktop/Projects/thenewboston-js/test.js'
  ]
}```

`node_modules` conains `axios, core-js, follow-redirects, thenewboston, tweetnacl`

**Comment by AbhayAysola** [comment]
> @AbhayAysola I get an error when running `npm install <tgz file path>` and then running a simple `test.js` file with the contents:
> 
> ```
> require("thenewboston")
> ```
> 
> ```
> node:internal/modules/cjs/loader:928
>   throw err;
>   ^
> 
> 
> Error: Cannot find module 'regenerator-runtime/runtime'
> Require stack:
> - /Users/mieszkokycermann/Desktop/Projects/thenewboston-js/node_modules/thenewboston/dist/index.js
> - /Users/mieszkokycermann/Desktop/Projects/thenewboston-js/test.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:769:27)
>     at Module.require (node:internal/modules/cjs/loader:997:19)
>     at require (node:internal/modules/cjs/helpers:92:18)
>     at Object.<anonymous> (/Users/mieszkokycermann/Desktop/Projects/thenewboston-js/node_modules/thenewboston/dist/index.js:101:1)
>     at Module._compile (node:internal/modules/cjs/loader:1108:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
>     at Module.load (node:internal/modules/cjs/loader:973:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
>     at Module.require (node:internal/modules/cjs/loader:997:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/Users/mieszkokycermann/Desktop/Projects/thenewboston-js/node_modules/thenewboston/dist/index.js',
>     '/Users/mieszkokycermann/Desktop/Projects/thenewboston-js/test.js'
>   ]
> }
> ```
> 
> `node_modules` contains `axios, core-js, follow-redirects, thenewboston, tweetnacl`
> 
> My `package.json` looks like this:
> 
> ```
> {
>   "dependencies": {
>     "thenewboston": "file:thenewboston-1.0.2.tgz"
>   }
> }
> ```

Hmm that is weird, I'll look into it. Thanks for letting me know about this :)

**Comment by AbhayAysola** [comment]
I'm getting the same error, and it works if I add `regenerator-runtime` to the projects dependencies. Not sure if that is the best fix though. What do you think? @Kycermann @zinoadidi

**Comment by Kycermann** [comment]
> I'm getting the same error, and its fixed if I install `regenerator-runtime` . Not sure if that is the best fix though. What do you think? @Kycermann @zinoadidi

If it's a dependency then sure let's do that!

**Comment by Kycermann** [comment]
I'm still getting errors. Let's jump on a call!

**Comment by zinoadidi** [comment]
@AbhayAysola @Kycermann 
I was doing a little looking around and found that the package 
require("regenerator-runtime/runtime.js"); was in dist index js file. 
It seems  babel is using it for something i am not sure entirely what 
but try the suggestions here https://stackoverflow.com/questions/55857804/cannot-find-module-regenerator-runtime-runtime
someone mentioned that installing @babel/polyfill fixed the issue for them and a whole lot of other options;
but try and see what comes

**Comment by Kycermann** [comment]
@AbhayAysola I tried with your latest branch, I get a completely different error. We should really go over this with screen share etc would be faster.

**Comment by Kycermann** [comment]
Ah @zinoadidi ofc it's a typescript issue lol
I'll look tomorrow

**Comment by AbhayAysola** [comment]
@Kycermann @zinoadidi I think it should work now.

**Comment by AbhayAysola** [comment]
@zinoadidi I'm pretty sure that `@babel/polyfill` is deprecated in favor of `core-js` and `regenerator-runtime`. - https://babeljs.io/docs/en/babel-polyfill . I did try uninstalling `regenerator-runtime` and installing `@babel/polyfill` and it still works. I also tried `@babel/runtime` instead of `regenerator-runtime` and it worked.

**Comment by Kycermann** [comment]
It works IT WORKS @zinoadidi merge this ASAP please. @AbhayAysola don't forget to increment the version number!!

**Comment by zinoadidi** [comment]
@AbhayAysola @Kycermann good job guys;
Version update will be done once per merge to master to better manage the deployment process.
you don't need to do it in the PR

**Review by zinoadidi — APPROVED** [review]

**Pull request merged**
