### PR TITLE
Send database synchronisable idempotent payment #57

### LINKED ISSUE #57: [Task] Send database synchronisable idempotent payment
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

The `PaymentHandler` allows us to easily send TNBC. What if we need to synchronise with a database?

Possible approaches with the existing `PaymentHandler`:
1. First update the database. Then send the money. Oh no, the database was updated but then sending failed because the code crashed or the bank went offline. Now the database thinks money was sent but it wasn't!
2. First send the money. Then update the database. Oh no, we sent the money but the database went offline so now it thinks that we didn't send the money.

Solution:
1. Create the transaction (and this API has to expose the transaction before it's sent)
2. Store the transaction in the database, marked as not sent
3. Broadcast the transaction. If the database goes down or the code fails before the transaction is broadcast, that's fine- we'll just try broadcasting again
4. Now we're 100% sure that step 3 is complete, mark the transaction as complete in the database. If this step fails, we're back at step 3 but that won't ever result in double payment- because the same transaction can't execute twice. Eventually the payment will succeed (or the database will show that the payment wasn't successful)

With this solution, the database state is correct at all points in time- no matter what goes wrong.

## Behavior

The `PaymentHandler` API should expose the abilities to create a transaction and expose the transaction. It should also expose a method to send a transaction (that the `PaymentHandler` created) to the bank.

```ts
const {bank, transaction} = PaymentHandler.createTransaction(account, targetAddress, amount);

// First store transaction and mark payment as sent all in one database transaction (atomically)
// If the next line fails, no payment is recorded as having been sent
await database.storeTransaction(transaction);

// Now we can try to broadcast it
// If the next line fails, that's ok because we can try again later and it won't result in double or missed payments
PaymentHandler.broadcastTransaction(bank, transaction);

// Now we're 100% sure that the transaction was sent
// If the next line fails, we'll end up trying to broadcast again but that's fine, it's the same transaction with each attempt
await database.markTransactionAsSent(transaction);
```

### PR DESCRIPTION
**Pull request by AbhayAysola**
closes #57 
Account Number: 8928526805de48e4bf2ed2a9b4b839e6b2603018ecdfbf4cffdb2065e01a3ed1

### CODE REVIEW

**Comment by Kycermann** [comment]
Note: does this work if the returned transaction is put through JSON.stringify and JSON.parse?

I'll take a better look later, on my phone at the moment.

**Comment by AbhayAysola** [comment]
@Kycermann Yeah it works if the transaction is put through JSON.stringify and JSON.parse

**Comment by Kycermann** [comment]
@AbhayAysola awesome thank you! This is exactly what we needed.

**Comment by zinoadidi** [comment]
@AbhayAysola Is it possible to add tests as well?

**Comment by AbhayAysola** [comment]
> @AbhayAysola Is it possible to add tests as well?

Yeah I think it could work.

**Comment by zinoadidi** [comment]
ok, let me know when its done and i will review it

**Comment by Kycermann** [comment]
@zinoadidi can we assign a bounty to this? Without tests I'd give it 500 or 1000. With tests, well I don't know how complex it is

**Comment by zinoadidi** [comment]
bounty assigned to #57

**Comment by AbhayAysola** [comment]
@zinoadidi can you merge this? I'll add the tests in another PR.

**Comment by zinoadidi** [comment]
We can, but subsequent PR's need to come with tests as well

**Comment by AbhayAysola** [comment]
> We can, but subsequent PR's need to come with tests as well
> And there is linting coming soon

We also need tests for Banks, Accounts, Validators, etc.

**Comment by zinoadidi** [comment]
Currently trying to resolve the issue with publishing.
Will create all kinds of tasks soon with bounties

**Comment by AbhayAysola** [comment]
> Currently trying to resolve the issue with publishing.
> Will create all kinds of tasks soon with bounties

Yeah makes sense. So you'll merge this PR and I'll make another one with tests?

**Review by zinoadidi — APPROVED** [review]

**Pull request merged**
