### PR TITLE
Implemented post request for bank blocks under primary-validator  😁😁

### LINKED ISSUE #47: [Task] Implement Bank Blocks Endpoint for Primary Validator
# Task

Contributors are able to complete this task and earn thenewboston coins.  Check out the labels to learn how much you can earn for contributing by completing this task.  Please make sure to be honest if you wish to contribute by saying you can't finish this and we can just un-assign you with no harm done!  There is no point in delaying tasks from being completed for miscommunication!

## Overview

Build a `addBankBlocks` method onto the `PrimaryValidator` class that sends a POST request to the `/bank_blocks` endpoint.  Refer to the [docs on this endpoint ](https://thenewboston.com/primary-validator-api/bank-blocks)for more information.

## Behavior

The developer should be able to put in the sender's `Account` object and the transactions to add to the blockchain.  They should also specify the node identifier of the bank that will be taking in the transactions.

```ts
class PrimaryValidator {
  // snip

  async addBankBlocks(bankIdentifier: string, balanceLock: string, transactions: Transaction[], account: Account) {
    /* your code */
  }

  // snip
}

```

### PR DESCRIPTION
**Pull request by nishp77**
Closes #47

### CODE REVIEW

**Comment by sno2** [comment]
Thanks, but it looks like you need to pull the changes for the payment handler.

**Comment by nishp77** [comment]
Sorry don't understand by what you mean by "payment handler"

**Comment by sno2** [comment]
> Sorry don't understand by what you mean by "payment handler"

There were changes in the repo since you cloned it.  Therefore, the `payment-handler.ts` file had not been created yet.  You need to run pull the changes from this repo to get the file.

image

**Comment by nishp77** [comment]
Sorry resolved the issue however it was weird that github didn't show the diff between the master branch of the project and my fork

**Review by sno2 — APPROVED** [review]
LGTM, thanks

**Pull request merged**
